product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Models/Adverts/AdvertListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fsd.Sebastian.Cs.Ex4.Web.Models.Adverts
{
    public class AdvertListModel
    {
        public IEnumerable<string> Adverts { get; set; }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Models/PagedLists/PagedListModel.cs
using PagedList;
using Fsd.Sebastian.Cs.Ex4.Web.Models.Products;

namespace Fsd.Sebastian.Cs.Ex4.Web.Models.PagedLists
{
    public class PagedListModel
    {
        public IPagedList<ProductModel> Products { get; set; }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Models/Products/ProductListModel.cs
using System.Collections.Generic;

namespace Fsd.Sebastian.Cs.Ex4.Web.Models.Products
{
    public class ProductListModel
    {
        public IEnumerable<ProductModel> Products { get; set; }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Models/Products/ProductModel.cs
using Fsd.Sebastian.Cs.Ex4.Data.Enums;
using Fsd.Sebastian.Cs.Ex4.Web.Attributes;
using System;
using System.ComponentModel.DataAnnotations;

namespace Fsd.Sebastian.Cs.Ex4.Web.Models.Products
{
    public class ProductModel
    {
        [Required(ErrorMessage = "This field is required")]
        public string Producer { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Model { get; set; }

        [Required(ErrorMessage = "This field is required")]        
        [GreaterThanZero(ErrorMessage = "Price must be greater than 0")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [TodayIsMax(ErrorMessage = "Must be today or before")]
        public DateTime Date { get; set; }

        [Required]
        public ProductType Type { get; set; }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Controllers/AdvertsController.cs
using Fsd.Sebastian.Cs.Ex4.Web.Models.Adverts;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Fsd.Sebastian.Cs.Ex4.Web.Controllers
{
    public class AdvertsController : Controller
    {
        public ActionResult Display()
        {
            return PartialView(new AdvertListModel
            {
                Adverts = new List<string>
                {
                    "reklama 1",
                    "reklama 12",
                    "reklama 123",
                    "reklama 1234",
                }
            });
        }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Controllers/HomeController.cs
using Fsd.Sebastian.Cs.Ex4.Services.Products;
using System.Web.Mvc;

namespace Fsd.Sebastian.Cs.Ex4.Web.Controllers
{
    public class PageController : Controller
    {
        private readonly IProductProvider _productProvider;

        public PageController(IProductProvider productProvider)
        {
            _productProvider = productProvider;
        }

        public ActionResult Home()
        {
            return View(_productProvider.GetProductsCount());
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Controllers/ProductsController.cs
using Fsd.Sebastian.Cs.Ex4.Services.Products;
using Fsd.Sebastian.Cs.Ex4.Services.Products.Sql;
using Fsd.Sebastian.Cs.Ex4.Web.Mappings;
using Fsd.Sebastian.Cs.Ex4.Web.Models.PagedLists;
using Fsd.Sebastian.Cs.Ex4.Web.Models.Products;
using PagedList;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace Fsd.Sebastian.Cs.Ex4.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductProvider _productProvider;

        public ProductsController(IProductProvider productProvider)
        {
            _productProvider = productProvider;
        }

        public ActionResult Products(int? page, int? items)
        {
            ProductListModel list = new ProductListModel
            {
                Products = _productProvider.GetAllProducts().Select(entity => ProductMapper.ToModel(entity))
            };

            int pageNumber = page ?? 1;
            int pageSize = items ?? list.Products.Count();

            PagedListModel pagedList = new PagedListModel
            {
                Products = list.Products.ToPagedList(pageNumber, pageSize)
            };

            return View(pagedList);
        }

        public ActionResult Details(string producer, string model)
        {
            return View(ProductMapper.ToModel(_productProvider.GetSelectedProduct(producer, model)));
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new ProductModel());
        }

        [HttpPost]
        public ActionResult Add(ProductModel product)
        {
            if (!ModelState.IsValid)
                return View(product);
            
            SqlSetter.Insert(product.Producer, product.Model, product.Price, product.Date, product.Type);

            return RedirectToAction("SuccessMessage", new { producer = product.Producer, model = product.Model });
        }
        
        public ActionResult SuccessMessage(string producer, string model)
        {
            return View(ProductMapper.ToModel(_productProvider.GetSelectedProduct(producer, model)));
        }
    }
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Adverts/Display.cshtml
@model AdvertListModel

<div style="background: midnightblue; color: goldenrod; padding: 2px 10px">
    <h4>Adverts</h4>
    <ul>
        @foreach (string item in Model.Adverts)
        {
            <li>@item</li>
        }
    </ul>
</div>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Page/About.cshtml
@{
    ViewBag.Title = "About";
}
@section PageTitle { About the author }

<div class="row">
    <div class="col-md-9">
        <div class="jumbotron">
            <h2>Sebastian Nasuta</h2>
        </div>
    </div>
    <div class="col-md-3">
        @Html.Action("Display", "Adverts")
    </div>
</div>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Page/Home.cshtml
@model int
@{
    ViewBag.Title = "Home";
}
@section PageTitle { Home page }

<div class="row">
    <div class="col-md-8">
        <div class="jumbotron">
            <h1>Hello!</h1>
            <p class="lead">
                We have @Model @(Model == 1 ? "product" : "products").
            </p>
        </div>
    </div>
    <div class="col-md-4">
        @Html.Action("Display", "Adverts")
    </div>
</div>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Products/Add.cshtml
@model ProductModel
@{
    ViewBag.Title = "Add";
}
@section PageTitle { Adding new product }

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-xs-2">Producer</div>
        <div class="col-xs-6">
            @Html.EditorFor(model => model.Producer)
            @Html.ValidationMessageFor(model => model.Producer)
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">Model</div>
        <div class="col-xs-6">
            @Html.EditorFor(model => model.Model)
            @Html.ValidationMessageFor(model => model.Model)
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">Price</div>
        <div class="col-xs-6">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">Production date</div>
        <div class="col-xs-6">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">Type</div>
        <div class="col-xs-6">
            @Html.EnumDropDownListFor(model => model.Type)
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-6">
            <input type="submit" value="Send" />
        </div>
    </div>
}

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Products/Details.cshtml
@model ProductModel
@{
    ViewBag.Title = "Details";
}
@section PageTitle { @Model.Producer @Model.Model }

<div class="row">
    <div class="col-md-6">
        <table class="table">
            <tr>
                <th>Producer:</th>
                <td>@Model.Producer</td>
            </tr>
            <tr>
                <th>Model:</th>
                <td>@Model.Model</td>
            </tr>
            <tr>
                <th>Price:</th>
                <td>&pound@(Model.Price)</td>
            </tr>
            <tr>
                <th>Production date:</th>
                <td>@Model.Date.ToShortDateString()</td>
            </tr>
            <tr>
                <th>Type:</th>
                <td>@Model.Type</td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        @Html.Action("Display", "Adverts")
    </div>
</div>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Products/Products.cshtml
@model PagedListModel
@{
    ViewBag.Title = "Products";
}
@section PageTitle { List of products }

<table class="table">
        <thead class="h4">
            <tr>
                <th>Producer</th>
                <th>Model</th>
                <th>Price</th>
                <th>Production date</th>
                <th>Type</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.Producer</td>
                    <td>@product.Model</td>
                    <td>&pound@(product.Price)</td>
                    <td>@product.Date.ToShortDateString()</td>
                    <td>@product.Type</td>
                    <td>@Html.ActionLink("details", "details", new { producer = product.Producer, model = product.Model })</td>
                </tr>
            }
        </tbody>
</table>

<div>@Html.ActionLink("Add new product", "Add")</div>

<div>
    @Html.PagedListPager((IPagedList)Model.Products, page => Url.Action("Products", "Products", new { page, items = Model.Products.PageSize }), PagedListRenderOptions.Classic)
</div>
<div>
    Items on page:
    @Html.ActionLink("5", "Products", new { page = 1, items = 5 }) |
    @Html.ActionLink("10", "Products", new { page = 1, items = 10 }) |
    @Html.ActionLink($"ALL ({Model.Products.TotalItemCount})", "Products", new { page = 1, items = Model.Products.TotalItemCount })
</div>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Products/SuccessMessage.cshtml
@model ProductModel
@{
    ViewBag.Title = "SuccessMessage";
}
@section PageTitle { New product }

<h2>@Model.Producer @Model.Model added successfully</h2>
<h3>@Html.ActionLink("Go to all products", "Products")</h3>

product-list-csproject/Fsd.Sebastian.Cs/Fsd.Sebastian.Cs.Ex4.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <h2 style="color: white">MUSIC EQUIPMENT - @RenderSection("PageTitle")</h2>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Page")</li>
                    <li>@Html.ActionLink("Products", "Products", "Products")</li>
                    <li>@Html.ActionLink("About", "About", "Page")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top: 80px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sebastian Nasuta</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>